import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";
import "./product.css";
import "./styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CookieConsent = () => {
  const scriptSrc = "https://dimensions-tag.cloudinary.com/all.js";
  const scriptSrc2 = "https://dimensions-3d-viewer.cloudinary.com/all.js";
  const scriptSrc3 = "product.js";

  return (
    <>
      <Script src={scriptSrc2} />
      <Script src={scriptSrc} />
      <Script src={scriptSrc3}></Script>
    </>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <CookieConsent />
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
